
<footer class="footer">
	<div class="container">
		<div class="row row-content bg-green">
			<div class="col-xs-12">
                <p style="padding:10px;"></p>
                <p align=center>© Copyright 2008-2017 <a href="http://www.paraschis.gr">Spyros Paraschis</a></p>
				<p align=center><small>Last database update on February 2nd, 2017.</small></p>
            </div>
		</div>
	</div>
</footer>