			<div id="header">
			<img src="images/header.jpg"/>
			</div>
			
			<div id="nav">
				<a href="index.php">Home</a>
				<a href="rankings.php">Rankings</a>
				<a href="players.php">Player stats</a>
				<a href="worldcups.php">World cups</a>
				<a href="tournaments.php">Tournaments</a>
				<a href="misc.php">Misc Stats</a>
				<a href="calendar.php">Calendar</a>				
        <a href="links.php">Links</a>
        <a href="about.php">About</a>
				<a href="mailto:spyros1973@yahoo.com">Contact</a>
			</div>
