    <div id="divModal" class="modal fade" role="dialog" tabindex="-1">
        <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header bg-grey">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="modalTitle"></h4>
            </div>
            <div class="modal-body">
				<div id="modalBody">
				</div>
            </div>
        </div>
        </div>
    </div>
