<?php
$stats=array (
"Most games played","Best attack avg","Best defense avg","Worst attack avg","Worst defense avg","Most goals scored","Most goals conceded","Most wins","Most draws","Most losses","Biggest win %","Biggest draw %","Biggest loss %","Most tournaments won","Most clean sheets","Most clean sheets %","Most games with no goals","Most games with no goals %","Played against most players","Played against most countries","Easiest opponent for more","Hardest opponent for more","Most games scored double figures","Most games conceded double figures","Games per month in the last year","Most dangerous","Least dangerous"
);

?>
